TO_STRING(cpp_void);
TO_STRING(cpp_bool);
TO_STRING(cpp_uchar);
TO_STRING(cpp_ushort);
TO_STRING(cpp_uint);
TO_STRING(cpp_ulong);
TO_STRING(cpp_ulonglong);
TO_STRING(cpp_uint128);
TO_STRING(cpp_schar);
TO_STRING(cpp_short);
TO_STRING(cpp_int);
TO_STRING(cpp_long);
TO_STRING(cpp_longlong);
TO_STRING(cpp_int128);
TO_STRING(cpp_float);
TO_STRING(cpp_double);
TO_STRING(cpp_longdouble);
TO_STRING(cpp_float128);
TO_STRING(cpp_char);
TO_STRING(cpp_wchar);
TO_STRING(cpp_char16);
TO_STRING(cpp_char32);
TO_STRING(cpp_nullptr);

CONST_STRING(                                          bool);
CONST_STRING(                                          unsigned char);
CONST_STRING(                                          unsigned short);
CONST_STRING(                                          unsigned int);
CONST_STRING(                                          unsigned long);
CONST_STRING(                                          unsigned long long);
//STATIC_TYPE                                          (unsigned __int128);
CONST_STRING(                                          signed char);
CONST_STRING(                                          short);
CONST_STRING(                                          int);
CONST_STRING(                                          long);
CONST_STRING(                                          long long);
//STATIC_TYPE                                          (__int128);
CONST_STRING(                                          float);
CONST_STRING(                                          double);
CONST_STRING(                                          long double);
//STATIC_TYPE                                          (__float128);
CONST_STRING(                                          char);
CONST_STRING(                                          wchar_t);
CONST_STRING(                                          char16_t);
CONST_STRING(                                          char32_t);
CONST_STRING(                                          nullptr);

CONST_STRING(cpp_bool, bool);
CONST_STRING(cpp_uchar, unsigned char);
CONST_STRING(cpp_ushort, unsigned short);
CONST_STRING(cpp_uint, unsigned int);
CONST_STRING(cpp_ulong, unsigned long);
CONST_STRING(cpp_ulonglong, unsigned long long);
CONST_STRING(cpp_uint128, unsigned __int128);
CONST_STRING(cpp_schar, signed char);
CONST_STRING(cpp_short, short);
CONST_STRING(cpp_int, int);
CONST_STRING(cpp_long, long);
CONST_STRING(cpp_longlong, long long);
CONST_STRING(cpp_int128, __int128);
CONST_STRING(cpp_float, float);
CONST_STRING(cpp_double, double);
CONST_STRING(cpp_longdouble, long double);
CONST_STRING(cpp_float128, __float128);
CONST_STRING(cpp_char, char);
CONST_STRING(cpp_wchar, wchar_t);
CONST_STRING(cpp_char16, char16_t);
CONST_STRING(cpp_char32, char32_t);
CONST_STRING(cpp_nullptr, nullptr);


STATIC_TYPE(bool, bool);
STATIC_TYPE(unsigned_char, unsigned char);
STATIC_TYPE(unsigned_short, unsigned short);
STATIC_TYPE(unsigned_int, unsigned int);
STATIC_TYPE(unsigned long, unsigned long);
STATIC_TYPE(unsigned long long, unsigned long long);
STATIC_TYPE(unsigned __int128, unsigned __int128);
STATIC_TYPE(signed char, signed char);
STATIC_TYPE(short, short);
STATIC_TYPE(int, int);
STATIC_TYPE(long, long);
STATIC_TYPE(long long, long long);
STATIC_TYPE(__int128, __int128);
STATIC_TYPE(float, float);
STATIC_TYPE(double, double);
STATIC_TYPE(long double, long double);
STATIC_TYPE(__float128, __float128);
STATIC_TYPE(char, char);
STATIC_TYPE(wchar_t, wchar_t);
STATIC_TYPE(char16_t, char16_t);
STATIC_TYPE(char32_t, char32_t);
STATIC_TYPE(nullptr, nullptr);
